vim.keymap.set('n', '<leader>db', require('dap').toggle_breakpoint)
vim.keymap.set('n', '<leader>dB', require('dap').clear_breakpoints)
vim.keymap.set('n', '<leader>dd', require('dap').continue)
vim.keymap.set('n', '<leader>dr', require('dap').repl.open)
vim.keymap.set('n', '<C-M-j>', require('dap').step_over)
vim.keymap.set('n', '<C-M-l>', require('dap').step_into)
vim.keymap.set('n', '<C-M-k>', require('dap').step_out)

vim.keymap.set('v', '<leader>de', require('dapui').eval)
vim.keymap.set('n', '<leader>dt', require('dapui').toggle)
