# vim:fileencoding=utf-8:foldmethod=marker

font_family      Berkeley Mono Variable
bold_font        Berkeley Mono Variable

modify_font underline_position +2

font_size 12.0

enabled_layouts tall, vertical, splits, stack, fat, grid, horizontal

# BEGIN_KITTY_THEME
# Rosé Pine
include current-theme.conf
# END_KITTY_THEME

map alt+q close_session .

map alt+s launch --type=overlay --copy-env ~/.local/bin/kitty-t
map alt+g launch --type=overlay --copy-env ~/.local/bin/kitty-s

map alt+shift+s goto_session -1

cursor_trail 3
cursor_trail_start_threshold 20
cursor_trail_color #ea9d34
cursor_blink_interval 0

cursor_shape block
shell_integration no-cursor

allow_remote_control yes
listen_on unix:/tmp/mykitty

map alt+t new_tab_with_cwd
map alt+w close_tab

map alt+x launch --location=hsplit --add-to-session=. --cwd=current
map alt+v launch --location=vsplit --add-to-session=. --cwd=current

map alt+enter new_window_with_cwd

map alt+m toggle_layout stack

map alt+j kitten pass_keys.py neighboring_window bottom alt+j
map alt+k kitten pass_keys.py neighboring_window top    alt+k
map alt+h kitten pass_keys.py neighboring_window left   alt+h
map alt+l kitten pass_keys.py neighboring_window right  alt+l

map alt+shift+h resize_window narrower
map alt+shift+l resize_window wider
map alt+shift+k resize_window taller
map alt+shift+j resize_window shorter

map alt+shift+x resize_window reset

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

map alt+r set_tab_title

map ctrl+alt+u scroll_page_up
map ctrl+alt+d scroll_page_down

map alt+shift+p command_palette

hide_window_decorations yes
macos_titlebar_color #000

macos_show_window_title_in none

window_padding_width 0 0 0

window_alert_on_bell no

tab_bar_style separator
tab_separator ""

tab_bar_align left
tab_powerline_style slanted

active_tab_font_style normal

tab_title_template "{fmt.bold}{fmt.fg._98be65} {' ' + session_name + ' ' if index == 1 and session_name else ''}{fmt.nobold}{fmt.fg.tab}{index}   {title} {fmt.fg._31748f}|"
active_tab_title_template "{fmt.bold}{fmt.fg._98be65} {' ' + session_name + ' ' if index == 1 and session_name else ''}{fmt.nobold}{fmt.fg.tab}{index}   {title}{'  ' if layout_name == 'stack' else ''} {fmt.fg._31748f}|"

startup_session ~/.config/kitty/default.kitty-session

tab_bar_min_tabs 1

scrollback_lines 10000

# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten '$HOME/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py'
# Browse scrollback buffer in nvim
map alt+shift+f kitty_scrollback_nvim
# Browse output of the last shell command in nvim
map alt+f kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
# Show clicked command output in nvim
mouse_map alt+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output

map alt+a launch --allow-remote-control kitty +kitten broadcast --match-tab state:focused

map alt+p scroll_to_prompt -1
map alt+n scroll_to_prompt 1

mouse_hide_wait	-1

map f1 create_marker
map f2 remove_marker

map alt+] launch --location=vsplit --add-to-session=. --cwd=current --keep-focus --bias=35 opencode --port --continue

globinclude kitty.d/**/*.conf

# No gap when underline overlaps other stuff
underline_exclusion 0
