# vim:fileencoding=utf-8:foldmethod=marker

font_family      Berkeley Mono Variable
bold_font        Berkeley Mono Variable
italic_font      Maple Mono NF CN

modify_font underline_position +2

font_size 12.0

enabled_layouts tall, vertical, splits, stack, fat, grid, horizontal

# BEGIN_KITTY_THEME
# Rosé Pine
include current-theme.conf
# END_KITTY_THEME

map alt+q close_session .

map cmd+s launch --type=overlay --copy-env ~/.local/bin/kitty-t
map cmd+g launch --type=overlay --copy-env ~/.local/bin/kitty-s

map cmd+shift+s goto_session -1

cursor_trail 3
cursor_trail_start_threshold 20
cursor_trail_color #ea9d34
cursor_blink_interval 0

cursor_shape block
shell_integration no-cursor

allow_remote_control yes
listen_on unix:/tmp/mykitty

map cmd+t new_tab_with_cwd
map cmd+w close_tab

map cmd+shift+x launch --location=hsplit --add-to-session=. --cwd=current
map cmd+shift+v launch --location=vsplit --add-to-session=. --cwd=current

map cmd+enter new_window_with_cwd

map cmd+m toggle_layout stack

map cmd+j kitten pass_keys.py neighboring_window bottom alt+j
map cmd+k kitten pass_keys.py neighboring_window top    alt+k
map cmd+h kitten pass_keys.py neighboring_window left   alt+h
map cmd+l kitten pass_keys.py neighboring_window right  alt+l

map cmd+shift+h resize_window narrower
map cmd+shift+l resize_window wider
map cmd+shift+k resize_window taller
map cmd+shift+j resize_window shorter

map cmd+shift+x resize_window reset

map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

map cmd+r set_tab_title

map cmd+u scroll_page_up
map cmd+d scroll_page_down
map cmd+e scroll_line_down
map cmd+y scroll_line_up

map cmd+shift+g scroll_end

map cmd+shift+p command_palette

hide_window_decorations yes
macos_titlebar_color #000

macos_show_window_title_in none

window_padding_width 0 0 0

window_alert_on_bell no

tab_bar_style separator
tab_separator ""

tab_bar_align left
tab_powerline_style slanted

active_tab_font_style normal

tab_title_template "{fmt.bold}{fmt.fg._98be65} {' ' + session_name + ' ' if index == 1 and session_name else ''}{fmt.nobold}{fmt.fg.tab}{index}   {title} {fmt.fg._31748f}|"
active_tab_title_template "{fmt.bold}{fmt.fg._98be65} {' ' + session_name + ' ' if index == 1 and session_name else ''}{fmt.nobold}{fmt.fg.tab}{index}   {title}{'  ' if layout_name == 'stack' else ''} {fmt.fg._31748f}|"

startup_session ~/.config/kitty/default.kitty-session

tab_bar_min_tabs 1

scrollback_lines 10000

# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten '$HOME/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py'
# Browse scrollback buffer in nvim
map cmd+shift+f kitty_scrollback_nvim
# Browse output of the last shell command in nvim
map cmd+f kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
# Show clicked command output in nvim
mouse_map cmd+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output

map cmd+a launch --allow-remote-control kitty +kitten broadcast --match-tab state:focused

map cmd+p scroll_to_prompt -1
map cmd+n scroll_to_prompt 1

mouse_hide_wait	-1

map f1 create_marker
map f2 remove_marker

map cmd+] launch --location=vsplit --add-to-session=. --cwd=current --keep-focus --bias=35 opencode --port --continue

globinclude kitty.d/**/*.conf

# No gap when underline overlaps other stuff
underline_exclusion 0
